import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../styles/main.css";
import BodyContent from "../components/BodyContent";

const inter = Roboto({ subsets: ["latin"], weight: '400' });

export const metadata: Metadata = {
  title: "Greg DiCristofaro",
  description: "Generated by create next app",
  icons: ["/img/favicon.png"]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BodyContent>
          {children}
        </BodyContent>
      </body>
    </html>
  );
}
